### ISSUE TITLE
Error when Launching Mapview Widget

### ISSUE THREAD

**Issue by Legohead259** [kivy-garden/mapview#13]
Hi,

I've started using mapview and had no issues during installation and example code works fine. However, whenever I try to launch the example code outside of the example directory (i.e. copying it verbatum to my own file in another directory) everything breaks. None of the imports register and upon launch of an unedited map with marker example, I get: 
```
 Traceback (most recent call last):
   File "D:/Projects/Halo Controller/tests/mapview_test.py", line 33, in <module>
     """)
   File "C:\Python27\lib\site-packages\kivy\lang\builder.py", line 350, in load_string
     parser = Parser(content=string, filename=fn)
   File "C:\Python27\lib\site-packages\kivy\lang\parser.py", line 392, in __init__
     self.parse(content)
   File "C:\Python27\lib\site-packages\kivy\lang\parser.py", line 498, in parse
     self.execute_directives()
   File "C:\Python27\lib\site-packages\kivy\lang\parser.py", line 464, in execute_directives
     mod = __import__('.'.join(package.split('.')[:-1]))
 ValueError: Empty module name
```

Does anyone know what's going on and/or how to fix it?

**Comment by AndreMiras** [comment]
I don't think it should be an issue with the new garden structure
