### ISSUE TITLE
Building from buildozer resultes in TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by guysoft** [kivy-garden/mapview#37]
**Describe the bug**
I am building the basic mapview example from the repo, I added

```
# (list) Garden requirements
garden_requirements = mapview
```

But when I build I get a build error.

```
Downloading http://github.com/kivy-garden/garden.mapview/archive/master.zip ...
Traceback (most recent call last):
  File "/home/guy/workspace/recycle_page/app/.buildozer/venv/bin/garden", line 189, in <module>
    GardenTool().main(sys.argv[1:])
  File "/home/guy/workspace/recycle_page/app/.buildozer/venv/bin/garden", line 71, in main
    options.func()
  File "/home/guy/workspace/recycle_page/app/.buildozer/venv/bin/garden", line 109, in cmd_install
    fd = self.download(opts.package)
  File "/home/guy/workspace/recycle_page/app/.buildozer/venv/bin/garden", line 170, in download
    data += buf
TypeError: can only concatenate str (not "bytes") to str

```

**To Reproduce**

1. 
main.py
```python
from kivy_garden.mapview import MapView, MapMarker
from kivy_garden.mapview.clustered_marker_layer import ClusteredMarkerLayer
from kivy.app import App

class MapViewApp(App):
    def build(self):
        layer = ClusteredMarkerLayer()
        
        a = MapMarker()
        # mapview.add_marker(, cls=MapMarker)
        layer.add_marker(lon=32.092, lat=34.807, cls=MapMarker)
        
        mapview = MapView(zoom=11, lat=32.092, lon=34.807)
        mapview.add_widget(layer)
        return mapview

MapViewApp().run()
```

Buildozer add:
```
garden_requirements = mapview
```

You can also run the command explicitly:

```
garden install --app mapview
```

run 
```
buildozer -v android debug deploy run
```

**Expected behavior**
Should build.

**Logs/output**
```
Downloading http://github.com/kivy-garden/garden.mapview/archive/master.zip ...
Traceback (most recent call last):
  File "/home/guy/workspace/recycle_page/app/.buildozer/venv/bin/garden", line 189, in <module>
    GardenTool().main(sys.argv[1:])
  File "/home/guy/workspace/recycle_page/app/.buildozer/venv/bin/garden", line 71, in main
    options.func()
  File "/home/guy/workspace/recycle_page/app/.buildozer/venv/bin/garden", line 109, in cmd_install
    fd = self.download(opts.package)
  File "/home/guy/workspace/recycle_page/app/.buildozer/venv/bin/garden", line 170, in download
    data += buf
TypeError: can only concatenate str (not "bytes") to str

```

**Platform (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version 3.8
 - master

**Additional context**
Latest kivy

**Comment by AndreMiras** [comment]
Thanks for the bug report, but using this as a `garden_requirements` is no longer required.
Use it as normal requirements instead and make sure your `buildozer` version is up to date

**Comment by guysoft** [comment]
Thanks used that as a workaround.  version 1.2.0 .

**Comment by guysoft** [comment]
Perhaps the buildozer init should not include ``garden_requirements`` field?
